package freeimage

// #cgo LDFLAGS: -lfreeimage
// #include <FreeImage.h>
import "C"

// C.FREE_IMAGE_FORMAT
const (
	UNKNOWN = C.FIF_UNKNOWN
	BMP     = C.FIF_BMP
	ICO     = C.FIF_ICO
	JPEG    = C.FIF_JPEG
	JNG     = C.FIF_JNG
	KOALA   = C.FIF_KOALA
	LBM     = C.FIF_LBM
	IFF     = C.FIF_IFF
	MNG     = C.FIF_MNG
	PBM     = C.FIF_PBM
	PBMRAW  = C.FIF_PBMRAW
	PCD     = C.FIF_PCD
	PCX     = C.FIF_PCX
	PGM     = C.FIF_PGM
	PGMRAW  = C.FIF_PGMRAW
	PNG     = C.FIF_PNG
	PPM     = C.FIF_PPM
	PPMRAW  = C.FIF_PPMRAW
	RAS     = C.FIF_RAS
	TARGA   = C.FIF_TARGA
	TIFF    = C.FIF_TIFF
	WBMP    = C.FIF_WBMP
	PSD     = C.FIF_PSD
	CUT     = C.FIF_CUT
	XBM     = C.FIF_XBM
	XPM     = C.FIF_XPM
	DDS     = C.FIF_DDS
	GIF     = C.FIF_GIF
	HDR     = C.FIF_HDR
	FAXG3   = C.FIF_FAXG3
	SGI     = C.FIF_SGI
	EXR     = C.FIF_EXR
	J2K     = C.FIF_J2K
	JP2     = C.FIF_JP2
	PFM     = C.FIF_PFM
	PICT    = C.FIF_PICT
	RAW     = C.FIF_RAW
)

// C.FREE_IMAGE_TYPE
const (
	TYPE_UNKNOWN = C.FIT_UNKNOWN
	TYPE_BITMAP  = C.FIT_BITMAP
	TYPE_UINT16  = C.FIT_UINT16
	TYPE_INT16   = C.FIT_INT16
	TYPE_UINT32  = C.FIT_UINT32
	TYPE_INT32   = C.FIT_INT32
	TYPE_FLOAT   = C.FIT_FLOAT
	TYPE_DOUBLE  = C.FIT_DOUBLE
	TYPE_COMPLEX = C.FIT_COMPLEX
	TYPE_RGB16   = C.FIT_RGB16
	TYPE_RGBA16  = C.FIT_RGBA16
	TYPE_RGBF    = C.FIT_RGBF
	TYPE_RGBAF   = C.FIT_RGBAF
)
